# This is a basic workflow to help you get started with Actions

name: Run-tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

      - name: Install tesseract
        run: sudo apt-get install -y tesseract-ocr

      - name: Install
        run: pip install --no-cache-dir --upgrade -r requirements.txt

      - name: Test
        run: python -m unittest discover -s tests